#!/usr/bin/env python3
"""
servers.dat parser - Test script
Parse MT5 server list file and get server name to IP address mappings.

Usage:
    python test_servers_dat.py <path_to_servers.dat>

Example:
    python test_servers_dat.py "/home/teamx/.wine/drive_c/Program Files/MetaTrader 5 EXNESS/Config/servers.dat"
"""

import sys
import os
from parse_servers_dat import parse_servers_dat


def test_parse():
    """Test the parser"""
    
    # Default path (Wine environment with Exness MT5)
    default_path = "/home/teamx/.wine/drive_c/Program Files/MetaTrader 5 EXNESS/Config/servers.dat"
    
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        filepath = default_path
    
    print("=" * 60)
    print("MT5 servers.dat Parser Test")
    print("=" * 60)
    print()
    
    # Check if file exists
    if not os.path.exists(filepath):
        print(f"Error: File not found - {filepath}")
        print()
        print("How to get servers.dat file?")
        print("-" * 40)
        print("1. Install MT5 terminal (download from broker website)")
        print("2. Run MT5 and login to your trading account")
        print("3. File location:")
        print("   - Windows: %APPDATA%\\MetaQuotes\\Terminal\\<hash>\\config\\servers.dat")
        print("   - Linux/Wine: ~/.wine/drive_c/users/<user>/AppData/Roaming/MetaQuotes/Terminal/<hash>/config/servers.dat")
        print("   - macOS: ~/Library/Application Support/MetaQuotes/Terminal/<hash>/config/servers.dat")
        print()
        print("Note: servers.dat is auto-generated by MT5 terminal, cannot be downloaded from internet.")
        sys.exit(1)
    
    print(f"Parsing: {filepath}")
    print(f"File size: {os.path.getsize(filepath)} bytes")
    print()
    
    # Parse the file
    servers = parse_servers_dat(filepath)
    
    # Display all servers
    print(f"Found {len(servers)} servers:")
    print()
    print(f"{'#':<6} {'Server Name':<35} {'Company':<30}")
    print("-" * 70)
    
    for s in servers:
        print(f"{s['index']:<6} {s['name']:<35} {s.get('company', '')[:30]:<30}")
    
    # Filter Exness servers
    exness_servers = [s for s in servers if 'exness' in s['name'].lower() or 'exness' in s.get('company', '').lower()]
    
    if exness_servers:
        print()
        print("=" * 60)
        print(f"Exness Servers ({len(exness_servers)})")
        print("=" * 60)
        print()
        
        for s in exness_servers:
            print(f"Server: {s['name']}")
            print(f"Company: {s.get('company', 'N/A')}")
            
            # Display AccessRec addresses
            for a in s.get('accesses', []):
                for addr in a.get('addresses', []):
                    print(f"  - {addr['address']}")
            
            # Display AccessRecEx addresses
            for a in s.get('accesses_ex', []):
                for addr in a.get('addresses', []):
                    print(f"  - {addr['address']}")
            
            print()
    
    # Test specific server lookup
    print("=" * 60)
    print("Test: Find specific servers")
    print("=" * 60)
    print()
    
    test_servers = ["Exness-MT5Trial17", "Exness-MT5Trial16", "Exness-MT5Real"]
    
    for test_name in test_servers:
        found = [s for s in servers if s['name'] == test_name]
        if found:
            s = found[0]
            print(f"[OK] Found server: {s['name']}")
            
            # Collect all IP addresses
            ips = []
            for a in s.get('accesses', []):
                for addr in a.get('addresses', []):
                    ips.append(addr['address'])
            for a in s.get('accesses_ex', []):
                for addr in a.get('addresses', []):
                    ips.append(addr['address'])
            
            if ips:
                print(f"  IP addresses: {', '.join(ips[:3])}{'...' if len(ips) > 3 else ''}")
            else:
                print(f"  No IP addresses found")
        else:
            print(f"[FAIL] Server not found: {test_name}")
        
        print()
    
    print("Test completed!")


if __name__ == '__main__':
    test_parse()
